cluster = false
address = "127.0.0.1:7001"
username = ""
password = ""
tls = false
db_type = "redis"  # redis, kvrocks, tair_mem, tair_scm, tair_ssd, garnet
output = ["xlsx", "json"]
replica_count = 0

# Leave empty to use all available CPUs. You can specify CPU cores,
# such as "0,1,6-10" to use cores 0, 1, 6, 7, 8, 9, and 10.
cpus = ""

[[cases]]
name = "STRING: SET 64B"
command = "SET {key uniform 50000000} {value 64}"
connections = 8
pipeline = 8
count = 100_000

[[cases]]
name = "SET: SISMEMBER"
dataset = { command = "SADD {key sequence 10} {key sequence 107}", count = 1007_000 }
command = "SISMEMBER {key uniform 10} {key uniform 1007}"
connections = 0
pipeline = 1
seconds = 10