cluster = false
address = "127.0.0.1:6379"
password = ""

[[cases]]
name = "NETWORK: ECHO 64B"
command = "ECHO {value 64}"
seconds = 120

[[cases]]
name = "NETWORK: PING with Pipeline"
command = "PING"
pipeline = 8
seconds = 120

[[cases]]
name = "NETWORK: ECHO 1024B"
command = "ECHO {value 1024}"
seconds = 120

[[cases]]
name = "STRING: SET 64B"
command = "SET {key uniform 50000000} {value 64}"
seconds = 120

[[cases]]
name = "STRING: GET 64B"
dataset = { command = "SET {key sequence 100000} {value 64}", count = 100000 }
command = "GET {key uniform 100000}"
seconds = 120

[[cases]]
name = "LIST: LPUSH 64B"
command = "LPUSH {key uniform 10000} {value 64}"
seconds = 120

[[cases]]
name = "LIST: LPOP 64B"
dataset = { command = "LPUSH {key sequence 1000} {value 8}", count = 1007_000 }
command = "LINDEX {key uniform 100} {rand 1007}"
seconds = 120

[[cases]]
name = "SET: SADD"
command = "SADD {key sequence 100000} {key sequence 1007}"
seconds = 120

[[cases]]
name = "SET: SISMEMBER"
dataset = { command = "SADD {key sequence 1000} {key sequence 1007}", count = 1007_000 }
command = "SISMEMBER {key uniform 1000} {key uniform 1007}"
seconds = 120

[[cases]]
name = "HASH: HSET 64B"
command = "HSET {key sequence 40000} {key sequence 1007} {value 16}"
seconds = 120

[[cases]]
name = "HASH: HGET 64B"
dataset = { command = "HSET {key sequence 1000} {key sequence 1007} {value 8}", count = 1007_000 } # 1007 elements
command = "HGET {key uniform 1000} {key uniform 1007}"
seconds = 120

[[cases]]
name = "ZSET: ZADD"
command = "ZADD {key uniform 30000} {rand 6000} {key sequence 1007}"
seconds = 120

[[cases]]
name = "ZSET: ZRANGEBYSCORE"
dataset = { command = "ZADD {key sequence 1000} {rand 1000} {value 8}", count = 1000_000 }
command = "ZRANGEBYSCORE {key uniform 1000} {range 1000 10}"
seconds = 120

[[cases]]
name = "LUA: SET 64B"
dataset = { command = '''SCRIPT LOAD "return redis.call('SET', KEYS[1], ARGV[1])"''', count = 1 }
command = "EVALSHA d8f2fad9f8e86a53d2a6ebd960b33c4972cacc37 1 {key uniform 100000} {value 64}"
seconds = 120
